AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Lambda function for github webhook

Resources:
  Hello:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bootstrap
      CodeUri: ./bin/bootstrap.zip
      Runtime: provided.al2023
      Timeout: 10
      Environment:
        Variables:
          ENV: dev
      Events:
        Index:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
