encryptionsalt: v1:cAPbxz5qq94=:v1:FoLbd7ETvxeBe6im:OrEs1FFO0KsQ536nwtkHcu28thRFGw==
config:
  aws:region: ap-southeast-2
  infrastructure:dbEndpoint: https://dynamodb.ap-southeast-2.amazonaws.com
  infrastructure:env: stage
  infrastructure:lambdaBasicExecRoleArn: arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  infrastructure:lambdaDynamoDBExecRoleArn: arn:aws:iam::aws:policy/service-role/AWSLambdaDynamoDBExecutionRole
  infrastructure:lambdaFunctionName: slack_pr_lambda
  infrastructure:lambdaRoleName: slack_pr_lambda_role
  infrastructure:region: ap-southeast-2
  infrastructure:slackChannel: pull-requests
  infrastructure:slackToken:
    secure: v1:FVsHmvKE0vS8RVEy:zHfzslqMAoTRCljZgpT9a4Ohya3/J+VfAlyNY6eAdx6VD5gKSh03JU8a9+Od5FGOzBouHs21GwY+8bd2uQXkwlVdVVbSQIn5PpHtebFSZR6WlsOxL1PzE7vUClE=
  infrastructure:tableName: PullRequests
  infrastructure:tableNameIndex: PullRequestIdIndex
  pulumi:tags:
    automated: "true"
    team: DevOps
    tool: pulumi
